### ISSUE TITLE
As a Submodule, absolute import may need changes

### ISSUE THREAD

**Issue by kangwonlee** [autodrive/utils3#23]
3d187b0 : when standalone all tests pass.   Unable to import when a submodule.

https://stackoverflow.com/questions/36190751/import-error-on-trying-to-import-a-submodule-that-imports-a-submodule

**Comment by autodrive** [comment]
Practically https://github.com/autodrive/utils3/commit/381d9c98f8dc7e380085123a4eff1e2168363d0d implemented the relative import
